### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [inikishin/ugc_sprint_1#1]
Проделана большая работа 👍 Можно немного доработать код:
1. В ETL я бы рекомендовал избегать использования enable_auto_commit, который [по умолчанию True](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html). C учетом того, что при чтении каждой записи из кафки происходит коммит смещения, во время перезагрузок сервиса батч будет сбрасываться, и данные будут теряться на совсем. Временная метка просмотра, вероятно, не самая важная информация, но с какими-нибудь другими данными этот подход мог и не пройти. В этом случае как вариант - выполнять коммит **только** после вставки в ClickHouse.
2. [Вот тут](https://github.com/inikishin/ugc_sprint_1/blob/8655a1566063ff15ab3c28974bd052f8c26e0de7/ugc_etl/extract.py#L61) нужно продумать вариант отправки не только по времени, но и по заполнению пачки определенного размера. Дело в том, что в высоконагруженной системе за 60 секунд, может прилететь миллионы записей.
3. Вот [в этом месте](https://github.com/inikishin/ugc_sprint_1/blob/8655a1566063ff15ab3c28974bd052f8c26e0de7/ugc_etl/extract.py#L55), нужно использовать логирование.
4. Вот этот [auth_url](https://github.com/inikishin/ugc_sprint_1/blob/8655a1566063ff15ab3c28974bd052f8c26e0de7/ugc_api/src/main.py#L22) лучше убрать в переменную окружения.
5. В `ugc_api/src/main.py` есть несколько неиспользуемых импортов.

**Comment by inikishin** [comment]
Все исправлено

**Comment by BigDeepBlue** [comment]
LGTM
